# Generated by Django 3.2.8 on 2021-11-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antegen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=5)),
                ('nex_coming', models.DateField()),
            ],
            options={
                'verbose_name': 'antegen',
                'verbose_name_plural': 'antegens',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=25)),
                ('loca_goverment', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'clinic',
                'verbose_name_plural': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=14)),
                ('card_number', models.CharField(max_length=10)),
                ('firs_name', models.CharField(max_length=25)),
                ('certificate_number', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('GENDER', 'Gender'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='GENDER', max_length=6)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='children.clinic')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
            },
        ),
    ]
