# Generated by Django 3.2.8 on 2021-12-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20211201_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antegen',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antegens', to='children.children'),
        ),
    ]
