# Generated by Django 3.2.8 on 2021-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_antegen_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='creates',
            field=models.DateField(auto_now=True),
        ),
    ]
